// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  // TODO (codelab user): Replace with your Firebase credentials

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGPcp51SrdPoZGt042Jtig3QvRts_sEOs',
    appId: '1:367270290274:web:d01451b73bb7e14f99423b',
    messagingSenderId: '367270290274',
    projectId: 'fir-interfaces-77188',
    authDomain: 'fir-interfaces-77188.firebaseapp.com',
    storageBucket: 'fir-interfaces-77188.appspot.com',
    measurementId: 'G-FKEGZ3G6KR',
  );

  // Generate this file with credentials with the FlutterFire CLI

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRrRfEfT5ULSBzIUeymGnZmk5wT0S62fc',
    appId: '1:367270290274:android:7c38d56a3fded8a499423b',
    messagingSenderId: '367270290274',
    projectId: 'fir-interfaces-77188',
    storageBucket: 'fir-interfaces-77188.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtuifr1fckwl1Vp-S-qo_ACLFiZbDCMFo',
    appId: '1:367270290274:ios:89913b7270ef4de199423b',
    messagingSenderId: '367270290274',
    projectId: 'fir-interfaces-77188',
    storageBucket: 'fir-interfaces-77188.appspot.com',
    iosClientId: '367270290274-42p7jetmtvtllgjb0ln0juuj68hau3g3.apps.googleusercontent.com',
    iosBundleId: 'com.example.start',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtuifr1fckwl1Vp-S-qo_ACLFiZbDCMFo',
    appId: '1:367270290274:ios:89913b7270ef4de199423b',
    messagingSenderId: '367270290274',
    projectId: 'fir-interfaces-77188',
    storageBucket: 'fir-interfaces-77188.appspot.com',
    iosClientId: '367270290274-42p7jetmtvtllgjb0ln0juuj68hau3g3.apps.googleusercontent.com',
    iosBundleId: 'com.example.start',
  );

}